- name: Create profiles
  firefox_profile:
    name: "{{ firefox_profile_name }}"
    state: present
  register: create_profile

- name: Install extensions
  firefox_addon:
    name: "{{ item }}"
    profile_path: "{{ create_profile.profile_path }}"
    state: present
  with_items:
    - "{{ firefox_profile_values.extensions }}"

- name: Install user prefs
  lineinfile:
    path: '{{ create_profile.profile_path }}/user.js'
    create: yes
    regexp: '^user_pref\("{{ item.key }}",\s*\S+?\);\s*$'
    line: "user_pref(\"{{ item.key }}\", {{ ('\"%s\"' | format(item.value)) if item.value is string else (item.value | lower) }});"
  with_items: '{{ firefox_profile_values.preferences | default({}) | dict2items }}'
