- name: Create profiles
  firefox_profile:
    name: "{{ firefox_profile.name }}"
    state: present
  register: create_profile

- name: Install extensions
  firefox_addon:
    name: "{{ item }}"
    state: present
    profile: "{{ create_profile.profile_name }}"
  with_items:
    - "{{ firefox_profile.extensions }}"

- name: Install user prefs
  lineinfile:
    path: '{{ create_profile.profile_path }}/user.js'
    create: yes
    regexp: '^user_pref\("{{ item.name }}",\s*\S+?\);\s*$'
    line: "user_pref(\"{{ item.name }}\", {{ ('\"%s\"' | format(item.value)) if item.value is string else (item.value | lower) }});"
  with_items: '{{ firefox_profile.preferences | default([]) | select("defined") | list }}'
