---
- name: Load vars
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "vars"

- name: Install Firefox
  ansible.builtin.package:
    name: "{{ firefox_package_name }}"
    state: present
  become: true

- name: Configure profiles
  ansible.builtin.include_tasks: configure_profile.yml
  with_dict: "{{ firefox_profiles }}"
  loop_control:
    loop_var: firefox_profile
  tags: firefox
