---
name: Tests

"on":
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 0"

defaults:
  run:
    working-directory: "staticdev.firefox"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          path: "staticdev.firefox"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install test dependencies
        # TODO: WWhen there is an ansible-lint release above 6.15.0 constrain it and install it through PyPI
        run: pip install --constraint=.github/workflows/constraints.txt ansible yamllint git+https://github.com/ansible/ansible-lint

      - name: Lint code
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - debian11  # Bullseye
          - debian10  # Buster
          - ubuntu2204  # Jammy
          - ubuntu2004  # Focal
          - fedora38
          - fedora37
          - centos8
          - rockylinux9
          - rockylinux8

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          path: "staticdev.firefox"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt pip
          python3 -m pip --version

      - name: Install test dependencies
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt ansible 'molecule-plugins[podman]' podman

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
