---
name: Tests

"on":
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 0"

defaults:
  run:
    working-directory: "staticdev.firefox"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          path: "staticdev.firefox"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: pip install --constraint=.github/workflows/constraints.txt ansible yamllint ansible-lint

      - name: Lint code
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - debian11 # Bullseye
          - debian10 # Buster
          - debian9 # Stretch
          - debian8 # Jessie
          - ubuntu2204 # Jammy
          # https://github.com/geerlingguy/docker-ubuntu2204-ansible/issues/6
          - ubuntu2004 # Focal
          - ubuntu1804 # Bionic
          - ubuntu1604 # Xenial
          - ubuntu1404 # Trusty  # archive
          - ubuntu1204 # Precise # archive
          - fedora38
          - fedora37
          - fedora36
          - fedora35
          - fedora33
          - fedora34
          - fedora32
          - fedora31
          - fedora30
          - fedora29
          - fedora27
          - fedora24 # archive
          - centos8
          - centos7
          - centos6
          - rockylinux9
          - rockylinux8

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          path: "staticdev.firefox"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt pip
          python3 -m pip --version

      - name: Install test dependencies
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt ansible 'molecule-plugins[podman]' podman

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
